### ISSUE TITLE
Add position relative to list items in styles

### ISSUE THREAD

**Issue by mrwweb** [mrwweb/clicky-menus#15]
I suspect almost everyone is already doing this, but I've realized that this should probably be in the default styles, otherwise, the placement of submenus is very unpredictable. Almost everyone already does this, but I think I should add it.

```css
.clicky-menu li {
    position: relative;
}
```
